import { useState } from 'react'

const LEGEND = [
  { color: '#ef4444', label: 'False claim' },
  { color: '#f59e0b', label: 'Emotional language' },
  { color: '#eab308', label: 'Unverified' },
  { color: '#71717a', label: 'Neutral' },
  { color: '#60a5fa', label: 'Named entity' },
]

const EXPAND_ITEMS = [
  { color: '#ef4444', label: 'Red highlight', desc: '— AI detected factual contradiction vs verified sources' },
  { color: '#f59e0b', label: 'Orange highlight', desc: '— Emotionally loaded or urgency-driven language detected' },
  { color: '#eab308', label: 'Yellow highlight', desc: "— Claim could not be verified; insufficient source data" },
  { color: '#71717a', label: 'Gray highlight', desc: '— Neutral/factual language, no flags raised' },
  { color: '#60a5fa', label: 'Blue underline', desc: '— Named entity (person, org, location) identified' },
]

export default function DisclaimerPanel() {
  const [expanded, setExpanded] = useState(false)

  return (
    <div className="disclaimer-wrapper">
      {/* Heatmap Legend Bar — always visible above disclaimer */}
      <div className="heatmap-legend-bar">
        {LEGEND.map(item => (
          <div key={item.label} className="legend-chip">
            <span className="legend-chip-dot" style={{ background: item.color }} />
            <span className="legend-chip-label">{item.label}</span>
          </div>
        ))}
      </div>

      {/* Disclaimer Panel */}
      <div className="disclaimer-panel" id="ai-disclaimer">
        {/* Header */}
        <div className="disclaimer-header">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#f59e0b" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0 }}>
            <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
            <line x1="12" y1="9" x2="12" y2="13"/>
            <line x1="12" y1="17" x2="12.01" y2="17"/>
          </svg>
          <span className="disclaimer-label">AI Disclaimer</span>
        </div>

        {/* Body Text */}
        <p className="disclaimer-body">
          This analysis is generated by an AI system and is intended as a research aid only.
          Highlighted phrases and verdict classifications reflect statistical patterns detected
          across our source network — they are not definitive statements of fact. False claims,
          satire, and opinion pieces may be misclassified. Source credibility scores are based
          on historical data and may not reflect current editorial standards. Do not use this
          output as the sole basis for publishing, legal, medical, or financial decisions.
          Always verify findings with primary sources and qualified experts.
        </p>

        {/* Secondary Line */}
        <p className="disclaimer-secondary">
          Confidence score reflects model certainty, not absolute truth. Last model update: March 2026.{' '}
          <a href="/methodology" className="disclaimer-link">View our methodology →</a>
        </p>

        {/* Expandable Detail */}
        <button
          className="disclaimer-expand-toggle"
          onClick={() => setExpanded(prev => !prev)}
          aria-expanded={expanded}
        >
          What does each highlight colour mean? {expanded ? '−' : '+'}
        </button>

        {expanded && (
          <div className="disclaimer-expand-content">
            <ul className="disclaimer-colour-list">
              {EXPAND_ITEMS.map(item => (
                <li key={item.label}>
                  <span className="colour-dot" style={{ background: item.color }} />
                  <span className="colour-label">{item.label}</span>
                  <span className="colour-desc">{item.desc}</span>
                </li>
              ))}
            </ul>
            <p className="disclaimer-note">
              Highlights are probabilistic, not deterministic. A red highlight does not guarantee
              the claim is false — it signals high disagreement across our source network.
            </p>
          </div>
        )}

        {/* Legal Micro-copy */}
        <p className="disclaimer-legal">
          Superman Vision does not guarantee accuracy. By using this tool you agree to our{' '}
          <a href="/legal/terms-of-service" className="disclaimer-legal-link">Terms of Service</a>{' '}
          and{' '}
          <a href="/legal/acceptable-use" className="disclaimer-legal-link">Acceptable Use Policy</a>.
        </p>
      </div>
    </div>
  )
}
